### ISSUE TITLE
Question on bot

### ISSUE THREAD

**Issue by agi1512** [GaJinKim/AreologyBot#2]
I did some experimenting with the code trying to get rid of errors on extractor productions. Did not succeded yet, but I think i'm on the right way, now i want make decision - 

- rather to pass this iteration (in case there is something that didnt update yet what causes errors), 

- or to try to check if there is available action on selected Drone.

What did i try else, adressing this problem:

- Tried but did not succeed on adding of list of `target_vespene`'s to check if `considered_vespene` is in this list. It selects proper vespene geyser, but still errors. Don't know why for now :(

But I think I managed to achieve consistency on executing "build order", often there were no spawning pool starting for me and as a result - loss. Did some changes on logic: changed `==`'s to `>=` and added dict `once = { 'needed_action' = True, ... }` for every needed action so if bot starts another worker on start there will for sure be Overseer deployed. And after action `'needed_action'` is set to `False`, so action does not repeat and next action proceeds.

I like what you are doing, want to take part in the project (soon i will do some pull requests basing on your "todo" list for now)

Message of this Issue is simple: please dont dissappear, i like your bot and i like that you are working on it :) 
I like that strategy of fast expanding, but it needs some kind of logic to defend against rushes. VS zerg on VeryHard it's 50:50 depending on decicion of a bot to rush with zerglings or to stall.

Can you share some thoughts on what are you planning to do so i can assist you? If you want to see my code in pull requests, reply me :)

**Comment by GajinKim** [comment]
Hey @agi1512! Sorry that I missed your message. I'm new to project collaborations and this is my first time sharing an open source project of my own. 

I haven't had much time to work on this project the past few months because I've been focusing on school and searching for a summer job (I got a job as a web developer at my school). Now that things have settled down for me, I plan to continue on this project.

I'm not sure whether your comment was posted before or after I divvied up my mega class into a hierarchy, but the `target_vespene` and the "build order" issues should be fixed. For reference, I've put all of my old code into a folder called: `AreologyBotLegacy` and the updated bot is under `AreologyBot`.

Regarding the TO-DO list, I'm either planning to move it to the readme text so that it's easier for others to view.

I know it's been quite a while since you've posted, but if you're still interested, I would love to have you on board! 

And don't worry, this time I'm here to stay :)
